<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\system;

use gamboamartin\errores\errores;
use gamboamartin\validacion\validacion;
use stdClass;
use Throwable;


class _ctl_base extends system{


    public array $childrens;

    /**
     * Alta base de controllers
     * @return array|stdClass
     * @version 4.31.1
     */
    final protected function alta_bd_base(): array|stdClass
    {
        $data_retorno = $this->data_retorno_base();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener datos de retorno', data: $data_retorno);
        }

        $valida = $this->validacion->valida_alta_bd(controler: $this);
        if(errores::$error){

            return $this->errores->error(mensaje: 'Error al validar datos', data: $valida);
        }

        $r_alta_bd = parent::alta_bd(header:false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al insertar accion',data:  $r_alta_bd);
        }

        $data = new stdClass();
        $data->r_alta_bd = $r_alta_bd;
        $data->data_retorno = $data_retorno;

        return $data;
    }

    /**
     * Integra los campos view de una vista para alta y modifica Metodo para sobreescribir
     * @return array
     * @version 0.262.38
     * @esfinal revisada
     */
    protected function campos_view(): array
    {
        return array();
    }

    /**
     * Genera los campos view basicos
     * @param array $init_data Datos previamente inicializados
     * @param stdClass $keys Keys a integrar
     * @return array
     * @version 8.36.0
     */
    final public function campos_view_base(array $init_data, stdClass $keys): array
    {
        if(!isset($keys->selects)){
            $keys->selects = array();
        }

        $selects = (new \base\controller\init())->select_key_input($init_data, selects: $keys->selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar select',data:  $selects);
        }
        $keys->selects = $selects;

        $campos_view = (new \base\controller\init())->model_init_campos_template(
            campos_view: array(),keys:  $keys, link: $this->link);

        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar campo view',data:  $campos_view);
        }
        return $campos_view;
    }

    /**
     * Integra los elementos base de una view
     * @return array|$this
     * @version 0.263.38
     */
    private function base(): array|static
    {

        $campos_view = $this->campos_view();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar campos_view',data:  $campos_view);
        }

        $this->modelo->campos_view = $campos_view;



        $this->inputs = new stdClass();
        $this->inputs->select = new stdClass();


        return $this;
    }

    final public function contenido_children(stdClass $data_view, string $next_accion, array $not_actions): array|string
    {

        $params = array();
        $params['next_seccion'] = $this->tabla;
        $params['next_accion'] = $next_accion;
        $params['id_retorno'] = $this->registro_id;

        $childrens = $this->children_data(
            namespace_model: $data_view->namespace_model, name_model_children: $data_view->name_model_children,
            params: $params, not_actions: $not_actions);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar inputs',data:  $childrens);
        }

        $class_css_table = array('table','table-striped');
        $id_css_table = array($data_view->name_model_children);

        $contenido_table = (new table())->table(childrens: $childrens, cols_actions: 4, data_view: $data_view,
            class_css_table: $class_css_table, id_css_table:$id_css_table );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener tbody',data:  $contenido_table);
        }
        $this->contenido_table = $contenido_table;
        return $contenido_table;
    }

    final protected function children_data(string $namespace_model, string $name_model_children, array $params,
                                     array $not_actions = array()): array
    {
        $inputs = $this->children_base();
        if(errores::$error){
            return $this->errores->error(
                mensaje: 'Error al generar inputs',data:  $inputs);
        }

        $childrens = $this->childrens(namespace_model: $namespace_model, name_model_children: $name_model_children,
            not_actions: $not_actions, params: $params, registro_id: $this->registro_id);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al integrar links',data:  $childrens);
        }

        $this->childrens = $childrens;
        return $this->childrens;
    }

    /**
     * Genera los datos de un children para view de controller
     * @return array|stdClass
     * @version 0.309.39
     */
    final protected function children_base(): array|stdClass
    {
        $registro = $this->init_data_children();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar registro',data:  $registro);
        }

        $inputs = $this->inputs_children(registro: $registro);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar inputs',data:  $inputs);
        }

        $retornos = $this->input_retornos();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener retornos',data:  $retornos);
        }

        return $inputs;
    }

    /**
     * Genera el conjunto de children paar templates views
     * @param string $namespace_model paquete
     * @param string $name_model_children modelo del children
     * @param array $not_actions Acciones a quitar de la lista
     * @param array $params parametros paar select
     * @param int $registro_id registro en proceso
     * @return array
     */
    private function childrens(string $namespace_model, string $name_model_children, array $not_actions,
                               array $params, int $registro_id): array
    {

        $valida = $this->valida_data_children(
            namespace_model: $namespace_model,name_model_children:  $name_model_children,registro_id:  $registro_id);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al validar datos',data:  $valida);
        }
        $childrens = $this->rows_children(
            namespace_model: $namespace_model,name_model_children:  $name_model_children, registro_id: $registro_id);

        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al integrar childrens',data:  $childrens);
        }
        $childrens = $this->childrens_con_permiso(childrens: $childrens, name_model_children: $name_model_children,
            not_actions: $not_actions, params: $params);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al integrar childrens',data:  $childrens);
        }

        return $childrens;
    }

    private function childrens_con_permiso(array $childrens, string $name_model_children, array $not_actions,
                                           array $params): array
    {
        $key_id = $this->key_id_children(name_model_children: $name_model_children);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al integrar key_id',data:  $key_id);
        }
        $childrens = $this->rows_con_permisos(key_id: $key_id, rows: $childrens, seccion: $name_model_children,
            not_actions: $not_actions, params: $params);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al integrar link',data:  $childrens);
        }
        return $childrens;
    }

    /**
     * Integra la base de inputs y botones de una vista de modificacion
     * @param array $keys_selects
     * @param array $params
     * @param array $params_ajustados
     * @return array|stdClass
     */
    final protected function base_upd(array $keys_selects, array $params, array $params_ajustados): array|stdClass
    {

        if(count($params) === 0){
            $params = (new \gamboamartin\system\_ctl_base\init())->params(controler: $this,params:  $params);
            if(errores::$error){
                return $this->errores->error(mensaje: 'Error al asignar params', data: $params);
            }
        }

        if(count($params_ajustados) === 0) {
            $params_ajustados['elimina_bd']['next_seccion'] = $this->tabla;
            $params_ajustados['elimina_bd']['next_accion'] = 'lista';
        }

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener inputs',data:  $inputs);
        }

        $this->buttons = array();
        $buttons = (new out_permisos())->buttons_view(controler:$this, not_actions: $this->not_actions,
            params: $params, params_ajustados: $params_ajustados);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar botones',data:  $buttons);
        }

        $data = new stdClass();
        $data->buttons = $buttons;
        $data->inputs = $inputs;
        $this->buttons = $buttons;
        return $data;
    }

    /**
     * Obtiene los datos de retorno
     * @return array|stdClass
     * @version 0.287.38
     */
    private function data_retorno(): array|stdClass
    {
        $seccion_retorno = $this->seccion_retorno();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener seccion retorno', data: $seccion_retorno);
        }

        $id_retorno = $this->id_retorno();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener id retorno', data: $id_retorno);
        }
        $data = new stdClass();
        $data->seccion_retorno = $seccion_retorno;
        $data->id_retorno = $id_retorno;

        return $data;
    }

    /**
     * Genera los datos de retorno despues de una transaccion de controller
     * @return array|stdClass
     * Retorna despues de transaccion con header
     * @version 0.305.39
     */
    final protected function data_retorno_base(): array|stdClass
    {
        $siguiente_view = (new actions())->init_alta_bd();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener siguiente view', data: $siguiente_view);
        }

        $data_retorno = $this->data_retorno();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener datos de retorno', data: $data_retorno);
        }
        $data_retorno->siguiente_view = $siguiente_view;
        return $data_retorno;
    }

    /**
     * Integra un filtro para get childrens
     * @param int $registro_id Registro id para filtro
     * @return array
     * @version 5.5.0
     */
    private function filtro_children(int $registro_id): array
    {
        if($registro_id <= 0){
            return $this->errores->error(mensaje: 'Error registro_id debe ser mayor a 0',data:  $registro_id);
        }
        $this->key_id_filter = trim($this->key_id_filter);
        if($this->key_id_filter === ''){
            return $this->errores->error(mensaje: 'Error $this->key_id_filter esta vacio',data:  $this->key_id_filter);
        }
        $filtro = array();
        $filtro[$this->key_id_filter] = $registro_id;
        return $filtro;
    }

    /**
     * Genera un filtro para ser utilizado en childrens y obtener los registros pertenecientes al parent
     * @param int $registro_id Registro en proceso
     * @return array
     * @version 7.99.3
     */
    private function genera_filtro_children(int $registro_id): array
    {
        if($registro_id <= 0){
            return $this->errores->error(mensaje: 'Error registro_id debe ser mayor a 0',data:  $registro_id);
        }

        $key_id_filter = $this->key_id_filter();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener key_id_filter',data:  $key_id_filter);
        }

        $filtro = $this->filtro_children(registro_id: $registro_id);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener filtro',data:  $filtro);
        }

        return $filtro;
    }

    /**
     * Inicializa loe elementos para un alta
     * @return array|stdClass|string
     * @version 10.3.0
     */
    final public function init_alta(): array|stdClass|string
    {

        $r_template = parent::alta(header:false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener template',data:  $r_template);
        }

        $base = $this->base();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al genera base',data:  $base);
        }

        return $r_template;
    }

    /**
     * Obtiene el id de retorno depsues de una transaccion
     * @return int
     * @version 0.285.38
     */
    private function id_retorno(): int
    {
        $id_retorno = -1;
        if(isset($_POST['id_retorno'])){
            $id_retorno = $_POST['id_retorno'];
            unset($_POST['id_retorno']);
        }
        return $id_retorno;
    }

    /**
     * Inicializa los elementos de datos de un children para una view
     * @return array|stdClass
     * @version 0.264.38
     */
    private function init_data_children(): array|stdClass
    {
        if($this->registro_id<=0){
            return $this->errores->error(mensaje: 'Error this->registro_id debe ser mayor a 0',
                data:  $this->registro_id);
        }

        $registro = $this->modelo->registro(registro_id: $this->registro_id, retorno_obj: true);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener registro',data:  $registro);
        }

        $this->key_id_row = $this->tabla.'_id';

        return $registro;
    }

    /**
     * Inicializa upd base view
     * @return array|stdClass|string
     * @version 0.267.38
     */
    final protected function init_modifica(): array|stdClass|string
    {
        if($this->registro_id<=0){
            return $this->errores->error(mensaje: 'Error registro_id debe ser mayor a 0', data: $this->registro_id);
        }

        $r_template = parent::modifica(header: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener template',data:  $r_template);
        }

        $base = $this->base();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al genera base',data:  $base);
        }
        return $r_template;
    }

    /**
     * Debe star sobreescrito en el controlador integrando todos los selects necesarios
     * @param stdClass $registro
     * @return stdClass|array
     * @version 0.265.38
     * @final rev
     */
    protected function inputs_children(stdClass $registro): stdClass|array
    {

        return new stdClass();
    }

    /**
     * Genera los input para retornos despues de transaccion
     * @return array|stdClass
     */
    final protected function input_retornos(): array|stdClass
    {
        $retornos = (new html_controler(html: $this->html_base))->retornos(registro_id: $this->registro_id,tabla:  $this->tabla);
        if(errores::$error){
            return $this->errores->error(
                mensaje: 'Error al obtener retornos',data:  $retornos);
        }

        $hidden_input_id = (new html_controler(html: $this->html_base))->hidden(name: $this->key_id_row, value: $this->registro_id);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener hidden_input_id',data:  $hidden_input_id);
        }

        if(!is_object($this->inputs)){
            $this->inputs = new stdClass();
        }


        $this->inputs->hidden_row_id = $hidden_input_id;
        $this->inputs->hidden_seccion_retorno = $retornos->hidden_seccion_retorno;
        $this->inputs->hidden_id_retorno = $retornos->hidden_id_retorno;
        return $this->inputs;
    }

    protected function inputs_base_alta(array $keys_selects): array|stdClass
    {
        $keys_selects['descripcion'] = new stdClass();
        $keys_selects['descripcion']->cols = 12;

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener inputs',data:  $inputs);
        }
        return $inputs;
    }

    /**
     * Integra un elemento para select de template
     * @param string $key Campo a integrar
     * @param string $key_val Key para asignar value
     * @param array $keys_selects Conjunto de parametros
     * @param string|bool|array|null $value Valor
     * @return array
     * @version 0.275.38
     */
    private function integra_key_to_select(string $key, string $key_val, array $keys_selects, string|bool|array|null $value ): array
    {
        $key = trim($key);
        if($key === ''){
            return $this->errores->error(mensaje: 'Error key esta vacio',data:  $key);
        }
        $key_val = trim($key_val);
        if($key_val === ''){
            return $this->errores->error(mensaje: 'Error key_val esta vacio',data:  $key_val);
        }
        if(!isset($keys_selects[$key])){
            $keys_selects[$key] = new stdClass();
        }
        $keys_selects[$key]->$key_val = $value;
        return $keys_selects;
    }

    private function key_id_children(string $name_model_children): string
    {
        return $name_model_children.'_id';
    }

    /**
     * Integra un id para filter children
     * @return string
     * @version 5.4.0
     */
    private function key_id_filter(): string
    {
        $this->key_id_filter = $this->tabla.'.id';
        return $this->key_id_filter;
    }

    /**
     * Integra los parametros de un key para select
     * @param int $cols N cols css
     * @param bool $con_registros integra rows en opciones si es true
     * @param array $filtro Filtro para result
     * @param string $key Name input
     * @param array $keys_selects keys precargados
     * @param int|null $id_selected Identificador para selected
     * @param string $label Etiqueta a mostrar
     * @param array $columns_ds Columnas para mostrar en select
     * @param bool $disabled Atributo disabled
     * @return array
     * @version 0.288.38
     */
    final protected function key_select(int $cols, bool $con_registros, array $filtro,string $key, array $keys_selects,
                                  int|null $id_selected, string $label, array $columns_ds = array(),
                                        bool $disabled = false): array
    {
        $key = trim($key);
        if($key === ''){
            return $this->errores->error(mensaje: 'Error key esta vacio',data:  $key);
        }
        $valida = (new validacion())->valida_cols_css(cols: $cols);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al validar cols',data:  $valida);
        }

        $label = $this->label_init(key: $key,label:  $label);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar label',data:  $label);
        }

        if(!isset($keys_selects[$key])){
            $keys_selects[$key] = new stdClass();
        }

        $keys_params = array('cols','con_registros','label','id_selected','filtro','columns_ds','disabled');

        foreach ($keys_params as $key_val){

            /**
             * REFACTORIZAR
             */
            if($key_val === 'id_selected'){
                if(is_null($id_selected)){
                    $id_selected = -1;
                }
            }
            if(!isset($$key_val)){
                return $this->errores->error(mensaje: 'Error key val no es una variable valida',data:  $key_val);
            }

            $value = $$key_val;
            if(isset($keys_selects[$key]->$key_val)){
                $value=$keys_selects[$key]->$key_val;
            }

            $keys_selects = $this->integra_key_to_select(key: $key,key_val:  $key_val,keys_selects:  $keys_selects,
                value:  $value);
            if(errores::$error){
                return $this->errores->error(mensaje: 'Error al integrar keys',data:  $keys_selects);
            }
        }



        return $keys_selects;
    }

    /**
     * @param array $keys_selects
     * @return array
     */
    final protected function key_select_base(array $keys_selects): array
    {
        $keys_selects['descripcion'] = new stdClass();
        $keys_selects['descripcion']->cols = 12;

        $keys_selects['codigo'] = new stdClass();
        $keys_selects['codigo']->disabled = true;
        return $keys_selects;
    }



    /**
     * Genera un label para input
     * @param string $key Key del campo
     * @return string|array
     * @version 0.270.38
     */
    private function label(string $key): string |array
    {
        $key = trim($key);
        if($key === ''){
            return $this->errores->error(mensaje: 'Error key esta vacio',data:  $key);
        }
        $label = trim($key);
        $label = str_replace('_', ' ', $label);
        return ucwords($label);
    }

    /**
     * Inicializa un elemento label
     * @param string $key Key de input
     * @param string $label Etiqueta de input
     * @return array|string
     * @version 0.272.38
     */
    private function label_init(string $key, string $label): array|string
    {
        $key = trim($key);
        if($key === ''){
            return $this->errores->error(mensaje: 'Error key esta vacio',data:  $key);
        }
        $label = trim($label);
        if($label === ''){
            $label = $this->label(key: $key);
            if(errores::$error){
                return $this->errores->error(mensaje: 'Error al generar label',data:  $label);
            }
        }
        return $label;
    }

    /**
     * Ajusta los elementos de salida de un alta bd
     * @param bool $header is header aplica redirect
     * @param stdClass $data_retorno datos de redirect para get
     * @param stdClass $result Resultado de la transaccion
     * @param bool $ws is ws muestra salida json
     * @return stdClass|void
     * @version 8.2.0
     */
    final protected function out_alta_bd(bool $header, stdClass $data_retorno, stdClass $result, bool $ws){
        if(!isset($data_retorno->siguiente_view)){
            $data_retorno->siguiente_view = '';
        }
        if($header){

            if($data_retorno->id_retorno === -1) {
                $data_retorno->id_retorno = $result->registro_id;
            }
            $this->retorno_base(
                registro_id:$data_retorno->id_retorno, result: $result,
                siguiente_view: $data_retorno->siguiente_view, ws:  $ws,seccion_retorno: $data_retorno->seccion_retorno);

        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($result, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                $error = (new errores())->error(mensaje: 'Error al maquetar JSON' , data: $e);
                print_r($error);
            }
            exit;
        }
        $result->siguiente_view = $data_retorno->siguiente_view;

        return $result;
    }

    protected function retorno(
        stdClass $data_retorno, bool $header, int $registro_id, mixed $result, bool $ws){
        if($header){
            if($data_retorno->id_retorno === -1) {
                $data_retorno->id_retorno = $registro_id;
            }

            $this->retorno_base(registro_id:$data_retorno->id_retorno, result: $result, siguiente_view: $data_retorno->siguiente_view,
                ws:  $ws,seccion_retorno: $data_retorno->seccion_retorno);

        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($result, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                $error = $this->errores->error(mensaje: 'Error al dar salida json', data: $e);
                print_r($error);
            }
            exit;
        }
        return $result;
    }

    /**
     * @param string $namespace_model
     * @param string $name_model_children
     * @param int $registro_id
     * @return array
     */
    private function rows_children(string $namespace_model, string $name_model_children, int $registro_id): array
    {
        $filtro = $this->genera_filtro_children(registro_id: $registro_id);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener filtro',data:  $filtro);
        }

        $model_children = $this->modelo->genera_modelo(modelo: $name_model_children,namespace_model: $namespace_model);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar modelo',data:  $model_children);
        }

        $r_children = $model_children->filtro_and(filtro:$filtro);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener r_children',data:  $r_children);
        }
        return $r_children->registros;
    }

    /**
     * Obtiene la seccion de retorno
     * @return string
     * @version 0.282.38
     */
    private function seccion_retorno():string{
        $seccion_retorno = $this->tabla;
        if(isset($_POST['seccion_retorno'])){
            $seccion_retorno = $_POST['seccion_retorno'];
            unset($_POST['seccion_retorno']);
        }
        return $seccion_retorno;
    }

    /**
     * @param array $keys_selects
     * @return array|stdClass
     */
    final protected function upd_base_template(array $keys_selects): array|stdClass
    {
        $keys_selects = $this->key_select_base(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al integrar keys selects base',data:  $keys_selects);
        }

        $base = $this->base_upd(keys_selects: $keys_selects, params: array(),params_ajustados: array());
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al integrar base',data:  $base);
        }
        return $base;
    }

    /**
     * Valida la entrada de datos para childrens
     * @param string $namespace_model Namespace del paquete
     * @param string $name_model_children Nombre del modelo
     * @param int $registro_id Registro en proceso
     * @return bool|array
     * @version 4.33.1
     */
    private function valida_data_children(string $namespace_model, string $name_model_children,
                                          int $registro_id): bool|array
    {
        $namespace_model = trim($namespace_model);
        if($namespace_model === ''){
            return $this->errores->error(mensaje: 'Error namespace_model esta vacio',data:  $namespace_model);
        }

        $name_model_children = trim($name_model_children);
        if($name_model_children === ''){
            return $this->errores->error(mensaje: 'Error name_model_children esta vacio',data:  $name_model_children);
        }

        $this->tabla = trim($this->tabla);
        if($this->tabla === ''){
            return $this->errores->error(mensaje: 'Error $this->tabla esta vacio',data:  $this->tabla);
        }

        if($registro_id<=0){
            return $this->errores->error(mensaje: 'Error $registro_id debe ser mayor a 0',data:  $registro_id);
        }
        return true;
    }

}
